### ISSUE TITLE
Project name is different between Github and NPM

### ISSUE THREAD

**Issue by rjmunro** [prettymuchbryce/http-status-codes#26]
Could you rename the project on github from node-http-status to http-status-codes to match the name on NPM? It's confusing to have 2 names, and it seems perfectly possible to use this without node.

Other than that, this is exactly perfectly what I was looking for to make it easy to remember all the HTTP codes when writing typescript - thanks for a great project.

**Comment by prettymuchbryce** [comment]
@rjmunro Good idea. Done. Thanks.
