### ISSUE TITLE
Not all Status Codes present

### ISSUE THREAD

**Issue by tekpartner** [prettymuchbryce/http-status-codes#31]
Not all Status Codes (https://httpstatuses.com/) are included.

**Comment by DarylWright** [comment]
If you read the block comment in `index.js`, it indicates that status codes in RFC documents are supported. Codes such as [599](https://httpstatuses.com/599) do not exist in any RFCs and are therefore not supported by this lib.

**Comment by asos-tomp** [comment]
RFC7725 (https://tools.ietf.org/html/rfc7725) standardises ` HTTP 451 Unavailable For Legal Reasons` - yet it is not included?

**Comment by prettymuchbryce** [comment]
If it has an RFC and reasonable usage in the wild then I'm happy to add it. I've created an issue for 451 (#45).

The main goal here is to avoid situations where status codes are proposed but then never officially approved, for example what happened with `103 Checkpoint`.

Please feel free to open an issue proposing new codes if you feel they meet this criteria.
