### ISSUE TITLE
Feature Request: add esm support

### ISSUE THREAD

**Issue by xiaoxiangmoe** [prettymuchbryce/http-status-codes#44]
Add esm support for [vite](https://github.com/vitejs/vite).

**Comment by prettymuchbryce** [comment]
@xiaoxiangmoe Thanks for opening an issue. Do you happen to know what we need to do to enable esm support?

Is it just a matter of adding a package.json "type" field?

**Comment by o-alexandrov** [comment]
@prettymuchbryce Thank you for this library, added a PR for it, please release when it'd be convenient for you.

**Comment by prettymuchbryce** [comment]
This is done.
