### ISSUE TITLE
Mark the module as side-effect-free

### ISSUE THREAD

**Issue by EvgenyOrekhov** [prettymuchbryce/http-status-codes#58]
See https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free.

This will allow a more efficient tree-shaking.

**Comment by prettymuchbryce** [comment]
Thanks @EvgenyOrekhov. I was not aware of this.

**Comment by EvgenyOrekhov** [comment]
Not sure whether it had an actual effect. BundlePhobia reports that every individual export is 3 KB: https://bundlephobia.com/result?p=http-status-codes@2.1.3-beta.0.

**Comment by prettymuchbryce** [comment]
I don't think it did. I think this is due to exporting the `StatusCodes` and `ReasonPhrases` as enums which causes the whole enum to be bundled.

I think it may be possible to support enums while also taking better advantage of tree shaking.

Some more discussion of this happening in #55.
