### ISSUE TITLE
No release information for v2.2.0

### ISSUE THREAD

**Issue by donat-ebp** [prettymuchbryce/http-status-codes#81]
For releases up to 2.1.4, there's release notes. Version 2.2.0 was published to npm 9 days ago, but there's no release information on GitHub at all.

Could you please provide such information so that an update to this version can be considered?

**Comment by s1moe2** [comment]
Was about to open this same issue. The new 2.2.0 release seems empty (only bumps the version on package*.json files and nothing else).

**Comment by prettymuchbryce** [comment]
Thanks @donat-ebp. I have added the release notes for `v2.2.0` as well I have added some documentation for this in the README so my future self does not make the same mistake. :)

@s1moe2 If you run `git diff v2.1.4 v2.2.0` you can see the changes for `v2.2.0`. TLDR; it adds the 421 `MISDIRECTED_REQUEST` status code from [RFC 7540](https://datatracker.ietf.org/doc/html/rfc7540#section-9.1.2).
