### ISSUE TITLE
Reorder of the status codes enums exported

### ISSUE THREAD

**Issue by JameelKhan9** [prettymuchbryce/http-status-codes#85]
I find my team looking through the enums for the correct status code to use. Would be really useful to have the ts file ordered and comment blocks inserted outlining http code groups 100, 200, 300, etc.

I am happy to have a look at contributing this.

**Comment by prettymuchbryce** [comment]
The TS file is generated by [this](https://github.com/prettymuchbryce/http-status-codes/blob/master/scripts/update-codes.ts#L76-L86) script. I don't see the harm in doing it, so feel free to submit a PR if you're so inclined.
