### ISSUE TITLE
Status Code: ``535`` : Incorrect authentication data

### ISSUE THREAD

**Issue by pacifiquem** [prettymuchbryce/http-status-codes#99]
the SMTP User Authentication details you have configured (or not configured) in your email settings.

**Comment by angellee177** [comment]
@prettymuchbryce @pacifiquem let me work on this.

**Comment by pacifiquem** [comment]
Sure @angellee177

**Comment by angelsupp** [comment]
btw, why i can't find 535 http code on [official documentation for http-response](https://datatracker.ietf.org/doc/html/rfc7231#section-6.6.1l)? @pacifiquem

**Comment by angellee177** [comment]
hi @pacifiquem , this feature is ready to review.
please help me to review the [PR](https://github.com/prettymuchbryce/http-status-codes/pull/100).

Cheers,
Angel.

**Comment by pacifiquem** [comment]
Sure @angellee177 I'll review it soon. hope @prettymuchbryce is around to merge it.

**Comment by prettymuchbryce** [comment]
Am I understanding correctly that this is a status code for SMTP, which is an email protocol?

I'm not convinced that these status codes belong in this library, which is for HTTP.

**Comment by pacifiquem** [comment]
That's true @prettymuchbryce this status code belongs to SMTP, since it's not supported we can close this as **not planned**
